name: HashLink Build

on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Installing Libraries
        shell: cmd
        run: |
          .\setup.bat

      - name: Building
        run: haxelib run lime build hl

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: EternalEngine-HL
          path: export/release/hl/bin
          if-no-files-found: error
