name: Mac Build

on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Installing Libraries
        run: |
          chmod +x ./setup.sh
          sh ./setup.sh

      - name: Building
        run: haxelib run lime build mac

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: EternalEngine-Mac
          path: export/release/mac/bin
          if-no-files-found: error
